# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

### Site Settings ###
title               : VQuilonR Portfolio
name                : VQuilonR Portfolio
description         : # >-this means to ignore newlines until "baseurl:"
                      Entusiasta de la vida y Tecnófilo a ratos.
                      Desarrollador en Big DATA e Inteligencia Artificial.
                      Impulsando el procesamiento del lengauaje natural en español con ayuda de un :coffee:.

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl             : "" # the subpath of your site, e.g. /blog
# baseurl             : "/portfolYOU"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url: "https://vquilon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository          : vquilon/vquilon.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme        : YoussefRaafatNasry/portfolYOU


# --- You don't need to touch anything below here (but you can if you want) --- #
# --- Config --- #
# The release of Jekyll Now that you're using
version: v4.2.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

### Plugins ###
plugins:
  - "jekyll-github-metadata"
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only
  - pages/surprise/**
  - pages/tools/tags.html
  - pages/tools/**.html

surprise_nav_exclude:
  - pages/**
  - pages/surprise/boxes/**

### Author Info ###
bundauthor: Víctor Quilón Ranera
author:
  name              : Víctor Quilón Ranera
  image             : https://avatars.githubusercontent.com/u/17545846?s=460&u=718c63407520e5308879bef85416412e3c2d6b36&v=4
# behance           : your_username
# dribbble          : your_username
  email             : v.quilonr@gmail.com
  facebook          : victor.quilonranera
  github            : vquilon
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : vquilonr-291194
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : vquilon
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


surprise_conf:
  title             : Sorpresa!
  description       : Hey Rubita, han sido unos dias dificiles pero de alguna forma quiero hacerte las cosas mas fáciles y hacerte el día a día mas cómodo, y darte pequeñas cosas que necesites y alguna que otra tontada. Tambien me gustaría compensarte por las cosas que hago... y por toda la situacion. Se que te vas a negar, pero por favor echale un vistazo.
  author            : MORENAZO
  birthday_girl     : RUBIA
  image             : /assets/surprise/img/main.jpg


# --- Misc --- #
# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

### Posts ###
# format of URL of your posts
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only
  surprise:
    output: true
    permalink: /surprise/:name
  tools:
    output: true
    permalink: /tools/:name



# --- Comments --- #
### Disqus ###
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
# disqus: ""

# disqus:
#   shortname: your-short-name-disqus                     # Your website Shortname on disqus

### Firebase ###
# https://www.smashingmagazine.com/2020/08/comment-system-firebase/


# --- Web Statistics Section --- #
### Analytics ###
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# analytics:
#   enabled: false                                        # Set true to enable analytics
#   google:
#     tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:
      path: "pages/surprise/**"
    values:
      sitemap: false
      layout: "secret_box_amz"
      permalink: /surprise/:name/
  - scope:
      path: "_surprise/**"
    values:
      sitemap: false
  - scope:
      path: ""
      type: "tools"
    values:                                  # Set to true to enable disqus comments
      layout: "page"
      title: :title
      permalink: /tools/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
### Exclude from processing ###
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/templates/
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - CNAME
  - "*.log"
  - _template_posts
  - .history
  - .vscode

# Build settings
theme: minima
